version: '3.7'
services:
  roman:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - release_version=docker-compose
    image: eu.gcr.io/wire-bot/roman
    ports:
      - 8080:8080
      - 8081:8081
      - 8082:8082
    environment:
      - DB_URL=jdbc:postgresql://db:5432/roman
      - DB_USER=roman
      - DB_PASSWORD=roman
      # randomly generated for local testing
      - APP_KEY=0fb0f7f1-99aa-456c-a2bd-9e1132d0e9f4
    depends_on:
      - db

  db:
    image: postgres:12.2
    # just for local development
    environment:
      - POSTGRES_USER=roman
      - POSTGRES_PASSWORD=roman
      - POSTGRES_DB=roman
    ports:
      - 5432:5432
    volumes:
      - roman-db:/var/lib/postgresql/data/

volumes:
  roman-db:
